version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.88.1"
runtime-versions:
      python: 3.8
    
phases:
  install:
    runtime-versions:
      docker: 18
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugoforduke01
      - cd - 
      - rm -rf /tmp/*
  build:
    commands:
      - rm -rf public
      - hugo --minify
      - aws s3 cp public/ s3://hugofoorduke01b --recursive
  post_build:
    commands:
      - echo Build completed on `date`
